### ISSUE TITLE
Firewire abst comment typo

### ISSUE THREAD

**Issue by davexparker** [ahartmanns/qcomp#104]
The `rounds` property in the `firewire_abst` MDP model has a typo. 

"Maximum" should be "minimum" in the comment, to avoid confusion.

https://github.com/ahartmanns/qcomp/blob/master/benchmarks/mdp/firewire_abst/firewire_abst.props#L3

This is also in the description field in the `index.json` file.

https://github.com/ahartmanns/qcomp/blob/master/benchmarks/mdp/firewire_abst/index.json#L48

I already fixed this is in the PRISM benchmark suite.

Strictly speaking, it's actually the property that is wrong, not the comment. But the "minimum" variant is still vaguely meaningful and it seems preferable not to change properties retrospectively if possible.

**Comment by ahartmanns** [comment]
Fixed in 91722c311a7160fa6919d1c56b9ea7a90b1721f3.
