### ISSUE TITLE
QComp 2020 Replication Package Link broken

### ISSUE THREAD

**Issue by tquatmann** [ahartmanns/qcomp#108]
I noticed that the [link](https://doi.org/10.5281/zenodo.3965313) to the replication package [on the QComp 2020 page](https://github.com/ahartmanns/qcomp/blob/494eeb5896191ca1334c4a6bf4cf3b83d9785482/competition/2020/index.html#L50) is broken. 

Actually, I think it is also broken in the published competition report which is a bit unfortunate.

**Comment by ahartmanns** [comment]
The links and DOI should be working now.
