### ISSUE TITLE
Undocumented properties Modest conversion

### ISSUE THREAD

**Issue by remco1112** [ahartmanns/qcomp#66]
The following models have undocumented properties:

- ftwc
- polling-system
- reentrant-queues
- brp-pta
- wlan-large

The extra properties seem to be created in the modest to jani conversion.

**Comment by ahartmanns** [comment]
Fixed in 2824da02560b292bb29e7b5dfe0cec45f6949b15 and a07d37b968b21dcdfbe8ad87fe9021bb25281606.
